name: Deploy to gh-pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Checkout branch
          uses: actions/checkout@v4

        - name: Clean install dependencies
          run: npm install

        - name: Build app
          run: npm run build
        
        - name: Purge
          run: npm run purge

        - name: deploy
          uses: peaceiris/actions-gh-pages@v3.9.3
          with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./dist
          env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
